### ISSUE TITLE
ffigen 使用sample.h生成结果的时候将include里面的全生成出来了

### ISSUE THREAD

**Issue by wuxq** [xuzhongpeng/ffi_sample#1]
您好，
  我参照您的代码，用ffigen生成的时候，发现整个include都生成出来了， 导致很多错误， 比如
  
![image](https://user-images.githubusercontent.com/1889069/178893428-b2dc3bb6-6258-44f9-9505-e2d79e1556e0.png)
 
这个怎么处理呢， 您这边有遇到这种问题吗

**Comment by xuzhongpeng** [comment]
可以参考下[ffigen](https://pub.dev/packages/ffigen)文档，headers下可以指定哪些文件的生成

**Comment by wuxq** [comment]
感谢回复， 我尝试过使用这个，由于需要导出这个， 
 `DART_EXPORT intptr_t InitDartApiDL(void *data);`， 其中 `DART_EXPORT` 是在 `include/dart_api.h` 里面定义的，
 但是这个文件里面的东西特别多，如果我包含了这个文件，就会出现很多不需要的东西， 
 我对c实在不是很熟悉，就是在看您这边给的案例和您的工程，但我看您处理得很好，我没能处理出来

**Comment by xuzhongpeng** [comment]
> 

比如你的头文件是`demo.h`，头文件中引入及使用`include/dart_api.h`并不会影响的，看看加上`include-directives`是否能解决你的问题
```
ffigen:
  headers:
    entry-points:
      - 'demo.h'
    include-directives: 
      - 'demo.h'
```
